import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Toaster} from '@/components/ui/toaster';
import {Sidebar, SidebarProvider} from '@/components/ui/sidebar';
import {ThemeProvider} from 'next-themes';
import SidebarContentComponent from '@/components/sidebar-content';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FinTrack',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class">\
          <SidebarProvider>
            <Sidebar collapsible="icon">
              <SidebarContentComponent />
            </Sidebar>
              {children}
            </SidebarProvider>\
          <Toaster />
        </ThemeProvider>\
      </body>
    </html>
  );
}


